on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  analyze-src-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: gpakosz/.tmux
      - name: Get latest commit hash
        id: latest-commit-hash
        run: |
          echo ::set-output name=latest_commit_hash::$(git rev-parse --short HEAD)
      - name: Check latest commit hash
        run: echo ::notice title=latest commit hash::${{ steps.latest-commit-hash.outputs.latest_commit_hash }}
    outputs:
      latest_commit_hash: ${{ steps.latest-commit-hash.outputs.latest_commit_hash }}

  analyze-dst-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Get latest src commit
        id: latest-src-commit-hash
        run: |
          echo ::set-output name=latest_src_commit_hash::$(git --no-pager log --pretty=format:"%s" HEAD -1 | cut -c 10-)
      - name: Check latest src commit hash
        run: echo ::notice title=latest src commit hash::${{ steps.latest-src-commit-hash.outputs.latest_src_commit_hash }}
    outputs:
      latest_src_commit_hash: ${{ steps.latest-src-commit-hash.outputs.latest_src_commit_hash }}

  patch:
    runs-on: ubuntu-latest
    needs: [ analyze-src-commit, analyze-dst-commit ]
    if: needs.analyze-src-commit.outputs.latest_commit_hash != needs.analyze-dst-commit.outputs.latest_src_commit_hash
    steps:
      - uses: actions/checkout@v2
        with:
          repository: gpakosz/.tmux
          path: src
      - uses: actions/checkout@v2
        with:
          ref: main
          path: dst
      - name: xdg
        run: |
          rm -rf src/.git
          cp -af ./src/. ./dst/
          cat src/.tmux.conf | sed 's/~\/.tmux/~\/.config\/tmux\/tmux/g' > dst/.tmux.conf
          cat src/.tmux.conf.local | sed 's/~\/.tmux/~\/.config\/tmux\/tmux/g' > dst/.tmux.conf.local
      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          branch: main
          cwd: dst
          default_author: github_actions
          message: xdg form ${{ needs.analyze-src-commit.outputs.latest_commit_hash }}
          pull: NO-PULL
          push: true
